---
#############################################################################
# Container Runtime Role - Handlers
#############################################################################

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
  become: true

- name: reload containerd
  systemd:
    name: containerd
    state: reloaded
  become: true
