---
#############################################################################
# kube-proxy - Configuration Tasks
#############################################################################

- name: Verify required certificates exist
  stat:
    path: "{{ item }}"
  register: cert_check
  failed_when: not cert_check.stat.exists
  loop:
    - "{{ client_ca_file }}"
    - "{{ tls_cert_file }}"
    - "{{ tls_private_key_file }}"

- name: Create kube-proxy configuration file
  template:
    src: kube-proxy-config.yaml.j2
    dest: "{{ kube_proxy_config_path }}"
    mode: '0644'

- name: Create systemd service file for kube-proxy
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
    mode: '0644'
  notify: restart kube-proxy

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
