---
#############################################################################
# kube-proxy - Installation Tasks
#############################################################################

- name: Create kube-proxy directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ kube_proxy_config_dir }}"

- name: Install kube-proxy binary
  copy:
    src: /tmp/kubernetes-download/kube-proxy
    dest: "{{ k8s_bin_dir }}/kube-proxy"
    mode: '0755'
    remote_src: yes

- name: Verify kube-proxy installation
  command: "{{ k8s_bin_dir }}/kube-proxy --version"
  register: kube_proxy_version
  changed_when: false

- name: Display kube-proxy version
  debug:
    msg: "{{ kube_proxy_version.stdout }}"

- name: Clean up download directory
  file:
    path: /tmp/kubernetes-download
    state: absent
