---
#############################################################################
# kubelet - Configuration Tasks
#############################################################################

- name: Verify required certificates exist
  stat:
    path: "{{ item }}"
  register: cert_check
  failed_when: not cert_check.stat.exists
  loop:
    - "{{ client_ca_file }}"
    - "{{ tls_cert_file }}"
    - "{{ tls_private_key_file }}"

- name: Create kubelet configuration file
  template:
    src: kubelet-config.yaml.j2
    dest: "{{ kubelet_config_path }}"
    mode: '0644'

- name: Create systemd service file for kubelet
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    mode: '0644'
  notify: restart kubelet

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
