---
#############################################################################
# kubelet - Installation Tasks
#############################################################################

- name: Create kubelet directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ kubelet_config_dir }}"
    - "{{ kubelet_pod_manifest_path }}"
    - /var/lib/kubernetes
    - /var/run/kubernetes

- name: Install kubelet binary
  copy:
    src: /tmp/kubernetes-download/kubelet
    dest: "{{ k8s_bin_dir }}/kubelet"
    mode: '0755'
    remote_src: yes

- name: Verify kubelet installation
  command: "{{ k8s_bin_dir }}/kubelet --version"
  register: kubelet_version
  changed_when: false

- name: Display kubelet version
  debug:
    msg: "{{ kubelet_version.stdout }}"

- name: Clean up download directory
  file:
    path: /tmp/kubernetes-download
    state: absent
