---
#############################################################################
# kubelet - Handlers
#############################################################################

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: reload kubelet
  systemd:
    name: kubelet
    state: reloaded
