---
#############################################################################
# kube-apiserver - Installation Tasks
#############################################################################

- name: Create Kubernetes directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ k8s_bin_dir }}"
    - "{{ k8s_config_dir }}"
    - "{{ k8s_manifests_dir }}"
    - /var/log/kubernetes

- name: Install kube-apiserver binary
  copy:
    src: /tmp/kubernetes-download/kube-apiserver
    dest: "{{ k8s_bin_dir }}/kube-apiserver"
    mode: '0755'
    remote_src: yes

- name: Verify kube-apiserver installation
  command: "{{ k8s_bin_dir }}/kube-apiserver --version"
  register: apiserver_version
  changed_when: false

- name: Display kube-apiserver version
  debug:
    msg: "{{ apiserver_version.stdout }}"

- name: Clean up download directory
  file:
    path: /tmp/kubernetes-download
    state: absent
