---
#############################################################################
# kube-scheduler - Configuration Tasks
#############################################################################

- name: Verify required certificates exist
  stat:
    path: "{{ item }}"
  register: cert_check
  failed_when: not cert_check.stat.exists
  loop:
    - "{{ client_ca_file }}"
    - "{{ tls_cert_file }}"
    - "{{ tls_private_key_file }}"

- name: Create scheduler configuration file
  template:
    src: kube-scheduler-config.yaml.j2
    dest: "{{ scheduler_config_path }}"
    mode: '0644'

- name: Create systemd service file for kube-scheduler
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    mode: '0644'
  notify: restart kube-scheduler

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
