---
#############################################################################
# etcd Role - Handlers
#############################################################################

- name: restart etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
  become: true

- name: reload etcd
  systemd:
    name: etcd
    state: reloaded
  become: true
