---
#############################################################################
# kube-scheduler - Handlers
#############################################################################

- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    daemon_reload: yes

- name: reload kube-scheduler
  systemd:
    name: kube-scheduler
    state: reloaded
